linters:
  SelectorDepth:
    max_depth: 6
  NestingDepth:
    max_depth: 6
  PropertySortOrder:
    order: smacss
    separate_groups: false
  Indentation:
    width: 4
  SingleLinePerSelector:
    enabled: false
  QualifyingElements:
    enabled: false
    allow_element_with_attribute: true
  VendorPrefix:
    enabled: true