language: node_js

node_js:
  - node

branches:
  only:
    - master

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      sh ./deploy-ghpages.sh;
    fi

env:
  global:
    - GH_REF: github.com/peermusic/peermusic.github.io.git
    - secure: s05Uliv5558hARduF7Sc+QN7eloRBZ9dA3VeXWFmkLKOeUGKBn3NBStupfGgonJ+vpZEOWzThMCNbrjyBHYREc5kko6nXneelh2wvAFkXm+rOh7no4wSMwp/VhKV7+Z9Itfmu+inWxJJ4QPaOWXUnggmQFfEumACJOpWIPr1C3SLktwSBu2Rd0HYrPjCZOBl970FUaVCS8SoluZTUZYTwxSLYZ7omvb+v0bIJvOcBY988wKQ2wDtBYymb8fbY2UzMJafpGCWRYNXvf5yusatC0Hv+4Laj6Ly26oYnjGJMDcnM1RpL9zx8jYgD5zsWcDBtZV4J85riBZiLsR01Bzf++oKWB7FGyzPXLd/MunReT44ETs5pzyod6CxIGztgs71pI2syffS4vItjJJ0Tp7hG2aVCEimpqUeHGh7U5usdedYWoi6NSDjrjV7nKJV9HzwkZfTppT2n1ANPyZHmXKCakkXIAU0rHK8cjVXK02PhJ4To0BWgjn+a3QBgCk1ICREqa7rMFtgvMMBYRLQI3ngc382zqA7GI4m/N0F0566WCagufItpqMRxy4fDSD87ZQO+OFqG0nFn4QSNkLfxcjJoSDmejGXEeu2V9gUQJYiy5GNi8tNgKt8hrQo2iW6vz8EoCP3mRwl2umkDT9X6ZmZTNMZxfqse6Rl73lDssuax8M=
