language: node_js

node_js:
  - node

branches:
  only:
    - master

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      sh ./deploy-ghpages.sh;
    fi

env:
  global:
    - GH_REF: github.com/peermusic/peermusic.github.io.git
    - secure: IItIZ7MzPdeUrYWhRqcEjml/QiI4h9tGSjrSh+O3Cbm27/fg3FQN8P8nqkzsyOXPtJoMoyZ+2RQgQt7+8+Gtcn/07Qz96Gejg0ONhisQWQG0Ksf1qxxO62K2O9Bg+aFd2myOiJc6TYMMmKbQEZ774Q5JNVRcqc5rkhmaKi8IUyTF6rneiLofczMncHsYzJihNgCovyfPz0WSzdktflOA82JNpfMT4zMzYjKfnJ07VAwygCz0yfrjVIey60fDiw5hgJJ9b2yAiv111pnxwBsyDWoC43tthNeRJVg/SnuGqTjzbMq35ppn3en8mWq1HU38RPLvbi2DgpT6NzWGRMNzTmkmE8bf3LF389CE0+0ZawK2EVJ7MCs+TusbzVnL/AUq3XcfAr2VTTXCBFGXSu98lUQVI2cgt0MEoiY0/LwyQeBJYE8yIrcoXPtCeRdYBPiyROdM0p/Q8H/d2QiNlbfalR1ebZVZWEymZu1F8xWHpVnKK7lth3l08IUInSaVTV3vj8Sh5pMdcyAkGMDL4UWS+NxiPYdD0iM4QT3onJlxWQlF0cAsKVfIuCo+CgKGA+R1CoWeE97XzvaEnm2XLfFU09SC6KTv8zcTt79CtdS8pK+qkNb2sAoFc/hERjvAcE4mjYU57glXvBskJfVVHN9RbXe6xOdS4t1TOwmv4UXg9KA=
